config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :customers do
    collection {get :search}
    resources :credit_items
  end
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :credit_items
end

app/models/credit_item.rb
class CreditItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :customer
  belongs_to :category

  validates :category_id, presence: true
  validates :value, presence: true

  def category_name
    category.try!(:name) || 'Deleted Category'
  end

  def self.balance
    sum(:value)
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  before_create :set_view_token

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /@/, message: "is not a valid email" }
  validates :customer_id, presence: true

  has_many :credit_items

  delegate :balance, to: :credit_items

  def self.search(query)
    where(
      arel_table[:first_name].matches("%#{query}%")
      .or(arel_table[:last_name].matches("%#{query}%"))
      .or(arel_table[:email].matches("%#{query}%"))
      ).limit(10)
  end

  def name
    "#{first_name} #{last_name}"
  end

  def for_autocomplete
    {label: name, value: id}
  end

  private

  def set_view_token
    self.view_token ||= SecureRandom.hex
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :role, inclusion: {in: %w(user admin)}
  attr_accessor :password

  has_many :credit_items

  def admin?
    role == 'admin'
  end

  def user?
    role == 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  include Pundit::Authorization
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_action :require_login
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action -> { authorize Category, :manage? }

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.valid?
      @category.save!
      redirect_to action: :index
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to action: :index
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/credit_items_controller.rb
class CreditItemsController < ApplicationController
  before_action :find_customer
  before_action -> { authorize @customer, :manage? }, except: :index

  def index
    if !current_user.try(:admin?)
      raise Pundit::NotAuthorizedError, 'invalid view token' unless params[:view_token] == @customer.view_token
    end

    @new_credit_item = @customer.credit_items.build
    @view_qr_code =  RQRCode::QRCode.new(customer_credit_items_url(@customer, view_token: @customer.view_token))
                                    .as_png(size: 240)

    @credit_items = @customer.credit_items
      .includes(:category)
      .order("updated_at DESC")
      .paginate(page: params[:page], per_page: 10)
  end

  def new
    if Category.count.zero?
      flash[:alert] = "Can not add credit items because no categories are registered"
      begin
        redirect_to(:back)
      rescue ActionController::RedirectBackError
        redirect_to root_path
      end
      return
    end

    @credit_item = @customer.credit_items.build
  end

  def create
    @credit_item = @customer.credit_items.build(credit_item_params)
    if @credit_item.valid?
      @credit_item.save!
      redirect_to customer_credit_items_path(@customer)
    else
      render :new
    end
  end

  private

  def find_customer
    @customer = Customer.find(params[:customer_id])
  end

  def credit_item_params
    params.require(:credit_item).permit(:category_id, :value, :note).merge({user_id: current_user.id})
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action -> { authorize Customer, :manage? }

  def index
    @customers = Customer.paginate(page: params[:page], per_page: 10)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.valid?
      @customer.save!
      redirect_to action: :index
    else
      render :new
    end
  end

  def search
    render json: Customer.search(params[:term]).map(&:for_autocomplete).to_json
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :postal_code, :customer_id, :email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @balance = CreditItem.balance
    @recent_transactions = RecentTransactions.call
    @highest_balances = HighestBalances.call
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = authenticate_session(session_params)
    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < AuthorizedController
  before_action -> { authorize User, :manage? }

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }.with_indifferent_access[flash_type] || flash_type.to_s
  end
end

app/views/categories/index.html.haml
%h2 Categories
- if @categories.any?
  %ul.list-group
    - @categories.each do |c|
      %li.list-group-item
        = c.name
        = link_to c, action: :destroy, method: :delete do
          %span.glyphicon.glyphicon-remove.pull-right
- else
  %h2 No categories yet
= link_to "Add Category", {action: :new}, class: 'button small'

app/views/categories/new.html.haml
= form_for @category do |f|
  .form-group{class: ("has-error" if @category.errors[:name].any?)}
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
    - if @category.errors[:name]
      - @category.errors[:fname].each do |e|
        %span.help-block= e

  .form-group
    = f.submit "Create Category"

app/views/credit_items/_credit_item_row.html.haml
%tr
  %td= credit_item.created_at.to_formatted_s(:long)
  %td= number_to_currency credit_item.value
  %td= credit_item.category_name
  %td= credit_item.note

app/views/credit_items/_form.html.haml
= form_for [customer, credit_item] do |f|
  .form-group{class: ("has-error" if credit_item.errors[:category].any?)}
    = f.label :category, class: 'control-label'
    = f.select :category_id, Category.all.map {|c| [c.name, c.id]}, class: 'form-control'
    - if credit_item.errors[:category]
      - credit_item.errors[:category].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if credit_item.errors[:value].any?)}
    = f.label :value, class: 'control-label'
    = f.number_field :value, class: 'form-control'
    - if credit_item.errors[:value]
      - credit_item.errors[:value].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if credit_item.errors[:note].any?)}
    = f.label :note, class: 'control-label'
    = f.text_area :note, class: 'form-control'
    - if credit_item.errors[:note]
      - credit_item.errors[:note].each do |e|
        %span.help-block= e

  .form-group
    = f.submit "Create", class: 'button small'

app/views/credit_items/_read_only_modal.html.haml
#readOnlyInfo.modal.fade.text-center{"data-reveal" => true, "aria-labelledby" => 'modalTitle', "aria-hidden" => "true", role: "dialog"}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", data: {dismiss: 'modal'}} &#215;
        %h3#modalTitle.modal-title Read-only information
      .modal-body
        %img{src: "data:image/png;base64,#{Base64.encode64(@view_qr_code.to_s)}"}
        %h5= link_to "Link", customer_credit_items_url(@customer, view_token: @customer.view_token)

app/views/credit_items/index.html.haml
%h4
  #{@customer.name}
  %small (Balance: #{number_to_currency @customer.balance})
  %p.pull-right
    %a{data: {toggle: 'modal', target: '#readOnlyInfo'}, href: '#'} Share

- if @credit_items.any?
  %table.table.table-striped
    %thead
      %tr
        %th Time
        %th Value
        %th Category
        %th Note
    %tbody
      = render partial: "credit_item_row", collection: @credit_items, as: :credit_item
  .text-center
    = will_paginate @credit_items

- else
  %h4 No entries yet

- if policy(@customer).manage?
  %hr
  %h4 Add entry
  = render partial: 'form', locals: {customer: @customer, credit_item: @new_credit_item}

= render partial: 'read_only_modal'

app/views/credit_items/new.html.haml
= render partial: 'form', locals: {customer: @customer, credit_item: @credit_item}

app/views/customers/_customer_row.html.haml
%tr
  %td= link_to customer.name, customer_credit_items_path(customer)
  %td= customer.email
  %td.show-for-large-up= customer.postal_code
  %td= customer.customer_id
  %td= number_to_currency(customer.balance)
  %td.show-for-large-up
    = link_to "Quick Add", new_customer_credit_item_path(customer)

app/views/customers/index.html.haml
- if @customers.any?
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th.show-for-large-up Postal code
        %th Customer ID
        %th Balance
        %th.show-for-large-up
    %tbody
      = render partial: "customer_row", collection: @customers, as: :customer
  .text-center
    = will_paginate @customers
- else
  %h2 No customers yet
= link_to "Add Customer", {action: :new}, class: 'button small'

app/views/customers/new.html.haml
= form_for @customer do |f|
  .form-group{class: ("has-error" if @customer.errors[:first_name].any?)}
    = f.label :first_name, class: 'control-label'
    = f.text_field :first_name, class: 'form-control'
    - if @customer.errors[:first_name]
      - @customer.errors[:first_name].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if @customer.errors[:last_name].any?)}
    = f.label :last_name, class: 'control-label'
    = f.text_field :last_name, class: 'form-control'
    - if @customer.errors[:last_name]
      - @customer.errors[:last_name].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if @customer.errors[:email].any?)}
    = f.label :email, class: 'control-label'
    = f.email_field :email, class: 'form-control'
    - if @customer.errors[:email]
      - @customer.errors[:email].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if @customer.errors[:postal_code].any?)}
    = f.label :postal_code, class: 'control-label'
    = f.text_field :postal_code, class: 'form-control'
    - if @customer.errors[:postal_code]
      - @customer.errors[:postal_code].each do |e|
        %span.help-block= e

  .form-group{class: ("has-error" if @customer.errors[:customer_id].any?)}
    = f.label :customer_id, "Customer ID", class: 'control-label'
    = f.text_field :customer_id, class: 'form-control'
    - if @customer.errors[:customer_id]
      - @customer.errors[:customer_id].each do |e|
        %span.help-block= e

  .form-group
    = f.submit "Create User"

app/views/home/index.html.haml
.panel.panel-green
  .panel-heading
    .row
      .col-xs-3
        = icon('money', class: 'fa-5x')
      .col-xs-9.text-right
        .huge
          #{number_to_currency @balance}
        %p
          Total outstanding
.panel.panel-default
  .panel-heading
    %h3 Recent transactions
  .panel-body
    %table.table.table-bordered.table-hover.table-striped
      %thead
        %tr
          %th Customer
          %th Category
          %th Value
      %tbody
        - @recent_transactions.each do |rt|
          %tr
            %td= rt.customer.name
            %td= rt.category_name
            %td= number_to_currency rt.value

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-lg-6
        %p.text-muted
          Copyright &copy; 2015 Bryan Alves. All rights reserved.
      .col-lg-6
        %p.text-muted.pull-right
          = link_to "Home", root_url
          = link_to "Github", 'https://www.github.com/bryanalves'

app/views/layouts/_messages.html.haml
- flash.each do |msg_type, msg|
  - if msg.is_a?(String)
    .alert.fade.in{class: bootstrap_class_for(msg_type)}
      %button.close{data: {dismiss: 'alert'}} x
      =msg

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Credit Ledger", root_url, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        - if policy(Customer).manage?
          %li= link_to "Manage Customers", customers_path
      .navbar-form.navbar-left
        .form-group
          = text_field :search, :term, class: 'header_customer_autocomplete form-control', placeholder: 'Customer quick search'

      %ul.nav.navbar-nav.navbar-right
        - if current_user.try(:admin?)
          %li.dropdown
            %a.dropdown-toggle{role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => false, data: {toggle: 'dropdown'}}
              Admin
              %span.caret
            %ul.dropdown-menu
              - if policy(Category).manage?
                %li= link_to "Manage entry categories", categories_path
              - if policy(User).manage?
                %li= link_to "Manage users", users_path
        - if signed_in?
          %li= link_to "Sign out", session_path, method: :delete
        - else
          %li= link_to "Sign in", new_session_path

app/views/layouts/application.html.haml
!!!
%head
  %meta{charset:"utf-8"}
  %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
  %meta{'http-equiv' => "X-UA-Compatible", content: "IE=edge"}

  %title
    = content_for?(:title) ? yield(:title) : "Credit Ledger"

  = stylesheet_link_tag  "application", media: 'all', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  = render 'layouts/nav'
  .container
    = render 'layouts/messages'
    = yield
  = render 'layouts/footer'
  = javascript_include_tag "application"

app/views/users/_user_row.html.haml
%tr
  %td= user.email

app/views/users/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Email
  %tbody
    = render partial: "user_row", collection: @users, as: :user
  .text-center
    = will_paginate @users

= link_to "Add User", {action: :new}, class: 'button small'

app/views/users/new.html.haml
= form_for @user do |f|
  .form-group
    = f.label :email, class: 'control-label'
    = f.email_field :email, class: 'form-control'

  .form-group
    = f.label :password, class: 'control-label'
    = f.password_field :password, class: 'form-control'

  .form-group
    = f.submit "Create"